objects/opportunity__c.object
<CustomObject>
    <fields>
        <fullName>EmailAddress__c</fullName>
        <label>EmailAddress</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <displayFormat>NO-{0000}</displayFormat>
        <label>OrderNumber</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>TableList__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TableList</label>
        <referenceTo>TableList__c</referenceTo>
        <relationshipLabel>opportunitys</relationshipLabel>
        <relationshipName>opportunitys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>stagename__c</fullName>
        <label>stagename</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>opportunity</label>
    <nameField>
        <label>opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>opportunitys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OrderTaking__c.object
<CustomObject>
    <fields>
        <fullName>opportunity__c</fullName>
        <label>opportunity</label>
        <referenceTo>opportunity__c</referenceTo>
        <relationshipLabel>OrderTakings</relationshipLabel>
        <relationshipName>OrderTakings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>price__c</fullName>
        <label>price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>product</label>
        <referenceTo>product__c</referenceTo>
        <relationshipLabel>OrderTakings</relationshipLabel>
        <relationshipName>OrderTakings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>quantity__c</fullName>
        <label>quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OrderTaking</label>
    <nameField>
        <label>OrderTaking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderTakings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/product__c.object
<CustomObject>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BreakFast</fullName>
                </value>
                <value>
                    <fullName>Lunch</fullName>
                </value>
                <value>
                    <fullName>Dinner</fullName>
                </value>
                <value>
                    <fullName>Snacks</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>price__c</fullName>
        <label>price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>product</label>
    <nameField>
        <label>product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Room_List__c.object
<CustomObject>
    <fields>
        <fullName>Base_Price__c</fullName>
        <label>Base Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Booking__c</fullName>
        <label>Current Booking</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RoomNo__c</fullName>
        <label>RoomNo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Deluxe</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Luxury</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Room List</label>
    <nameField>
        <label>Room List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Room List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RoomBooking__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Paid__c</fullName>
        <label>Amount Paid</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Check_In__c</fullName>
        <label>Check In</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Out__c</fullName>
        <label>Check Out</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Guest_Mobile__c</fullName>
        <label>Guest Mobile</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Guest_Name__c</fullName>
        <label>Guest Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Room_Link__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Room Number</label>
        <referenceTo>Room_List__c</referenceTo>
        <relationshipLabel>Room Link</relationshipLabel>
        <relationshipName>Room_Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Room Booking</label>
    <nameField>
        <displayFormat>KTM-{000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Room Booking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TableList__c.object
<CustomObject>
    <fields>
        <fullName>NoOfPerson__c</fullName>
        <label>NoOfPerson</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Serving</fullName>
                </value>
                <value>
                    <fullName>ReadyForBill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TableNo__c</fullName>
        <label>TableNo</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>opportunitynew__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>opportunity</label>
        <referenceTo>opportunity__c</referenceTo>
        <relationshipLabel>TableLists</relationshipLabel>
        <relationshipName>TableLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TableList</label>
    <nameField>
        <label>TableList Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TableLists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Util_UTC.cls
@isTest
private class Util_UTC {
    public static opportunity__c opp;
    public static TableList__c table;
    public static RoomBooking__c rbooking;
    public static Room_List__c room;

    static {



        opp = new opportunity__c();
        opp.EmailAddress__c = 'udhay@gmail.com';
        //opp.OrderNumber__c ='100';
        //stagename__c ='';
        //status__c='';
        //TableList__c
        //type__c
        insert opp;


        table = new TableList__c();
        table.NoOfPerson__c = '1';
        table.opportunitynew__c = opp.id;
        table.Status__c = 'Available';
        table.TableNo__c = Decimal.valueof('1');
        insert table;

        ApexPages.currentPage().getParameters().put('sid', table.id);



        product__c prod = new product__c();
        prod.Family__c = 'Lunch';
        prod.price__c = Decimal.valueof('100.00');
        prod.name = 'Meals';
        insert prod;

        OrderTaking__c order = new OrderTaking__c();
        order.price__c = Decimal.valueof('1000.00');
        order.quantity__c = Decimal.valueof('1');
        order.status__c = 'Available';
        order.opportunity__c = opp.id;
        order.product__c = prod.id;
        insert order;





        room = new Room_List__c();
        room.Base_Price__c = Decimal.valueof('100.00');
        //Current_Booking__c
        room.RoomNo__c = Decimal.valueof('1');
        room.Status__c = 'Booked';
        room.Type__c = 'Deluxe';
        room.name = '1';
        insert room;



        rbooking = new RoomBooking__c();
        rbooking.Room_Link__c = room.id;
        rbooking.Amount_Paid__c = Decimal.valueof('1000.00');
        rbooking.Check_In__c = date.today();
        rbooking.Check_Out__c = date.today() + 2;
        rbooking.Guest_Mobile__c = '63663632';
        rbooking.Guest_Name__c = 'Guest';

        insert rbooking;





    }
 
    static testMethod void validateRoomControl() {
        RoomController r = new RoomController();

    }
     

}