objects/opportunity__c.object
<CustomObject>
    <fields>
        <fullName>EmailAddress__c</fullName>
        <label>EmailAddress</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <displayFormat>NO-{0000}</displayFormat>
        <label>OrderNumber</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>TableList__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TableList</label>
        <referenceTo>TableList__c</referenceTo>
        <relationshipLabel>opportunitys</relationshipLabel>
        <relationshipName>opportunitys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>opportunity</label>
    <nameField>
        <label>opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>opportunitys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OrderTaking__c.object
<CustomObject>
    <fields>
        <fullName>opportunity__c</fullName>
        <label>opportunity</label>
        <referenceTo>opportunity__c</referenceTo>
        <relationshipLabel>OrderTakings</relationshipLabel>
        <relationshipName>OrderTakings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>price__c</fullName>
        <label>price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>product</label>
        <referenceTo>product__c</referenceTo>
        <relationshipLabel>OrderTakings</relationshipLabel>
        <relationshipName>OrderTakings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>quantity__c</fullName>
        <label>quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderTaking</label>
    <nameField>
        <label>OrderTaking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderTakings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/product__c.object
<CustomObject>
    <fields>
        <fullName>price__c</fullName>
        <label>price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>product</label>
    <nameField>
        <label>product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TableList__c.object
<CustomObject>
    <label>TableList</label>
    <nameField>
        <label>TableList Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TableLists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BillDetailsHandler.cls
global class BillDetailsHandler {
    global static String OpportuntiyId {
        get;
        set;
    }
    public List < Data > getData() {
        return BillDetailsHandler.getChartData(OpportuntiyId);
    }
        public Customer getCustomerData() {
        opportunity__c opplst = [SELECT id, Name, OrderNumber__c, LastModifiedDate, TableList__r.name, EmailAddress__c from opportunity__c WHERE Id = :OpportuntiyId limit 1];
        Customer c = new Customer();
        c.Name = opplst.name;
        c.OrderNo = opplst.OrderNumber__c;
        c.TableName = opplst.TableList__r.name;
        c.Email = opplst.EmailAddress__c;
        c.CDate = String.valueof(opplst.LastModifiedDate);
        return c;
    }

    global static List < Data > getChartData(String opd) {
        Map < String,
        String > fldMapings = new Map < String,
        String > ();
        List < Data > data = new List < Data > ();
        List < OrderTaking__c > qplist = [SELECT Name, price__c, Product__r.name, quantity__c from OrderTaking__c WHERE Opportunity__r.id = :opd];
        for (OrderTaking__c qp: qplist) {
            Data d = new Data();
            d.quantity = String.valueof(qp.quantity__c);
            d.product = qp.Product__r.name;
            d.price = String.valueof(qp.price__c);
            data.add(d);
        }
        return data;
    }
global class Data {
        public String Name {
            get;
            set;
        }
        public String price {
            get;
            set;
        }
        public String product {
            get;
            set;
        }
        public String quantity {
            get;
            set;
        }
        public Data() {}
    }

    global class Customer {
        public String Name {
            get;
            set;
        }
        public String CDate {
            get;
            set;
        }
        public String OrderNo {
            get;
            set;
        }
        public String TableName {
            get;
            set;
        }
        public String Email {
            get;
            set;
        }
        public Customer() {}
    }
    

 
}