objects/opportunity__c.object
<CustomObject>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <displayFormat>NO-{0000}</displayFormat>
        <label>OrderNumber</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>TableList__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TableList</label>
        <referenceTo>TableList__c</referenceTo>
        <relationshipLabel>opportunitys</relationshipLabel>
        <relationshipName>opportunitys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>stagename__c</fullName>
        <label>stagename</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>type__c</fullName>
        <label>type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>opportunity</label>
    <nameField>
        <label>opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>opportunitys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OrderTaking__c.object
<CustomObject>
    <fields>
        <fullName>opportunity__c</fullName>
        <label>opportunity</label>
        <referenceTo>opportunity__c</referenceTo>
        <relationshipLabel>OrderTakings</relationshipLabel>
        <relationshipName>OrderTakings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>price__c</fullName>
        <label>price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>product</label>
        <referenceTo>product__c</referenceTo>
        <relationshipLabel>OrderTakings</relationshipLabel>
        <relationshipName>OrderTakings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>quantity__c</fullName>
        <label>quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <label>status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OrderTaking</label>
    <nameField>
        <label>OrderTaking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderTakings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/product__c.object
<CustomObject>
    <fields>
        <fullName>price__c</fullName>
        <label>price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>product</label>
    <nameField>
        <label>product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TableList__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Booked</fullName>
                </value>
                <value>
                    <fullName>Serving</fullName>
                </value>
                <value>
                    <fullName>ReadyForBill</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>opportunitynew__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>opportunity</label>
        <referenceTo>opportunity__c</referenceTo>
        <relationshipLabel>TableLists</relationshipLabel>
        <relationshipName>TableLists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TableList</label>
    <nameField>
        <label>TableList Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TableLists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ServiceOrderController.cls
public with sharing class ServiceOrderController {

    public List < resultOrder > takeawayroList {
        get;
        set;
    }

    public List < resultOrder > roList {
        get;
        set;
    }
    public class resultOrder {
        public String tableName {
            get;
            set;
        }
        public String opprID {
            get;
            set;
        }
        public List < OrderTaking__c > ot {
            get;
            set;
        }

        //This is the contructor method. When we create a new wrapAccount object we pass a Account that is set to the acc property. We also set the selected value to false
        public resultOrder(String name, String oppid, List < OrderTaking__c > o) {
            tableName = name;
            opprID = oppid;
            ot = o;

        }
    }

    Public String updateOppId {
        get;
        set;
    }
    Public String updatetableID {
        get;
        set;
    }

    Public List < OrderTaking__c > opp {
        get;
        set;
    }
    Public List < OrderTaking__c > takeawayopp {
        get;
        set;
    }
    Public List < string > oppStr = new List < string > ();

    public PageReference deliver() {
        if (updateOppId != null) {
            List < OrderTaking__c > updateOrder = new List < OrderTaking__c > ();
            List < TableList__c > updateTab = [select id, status__C from TableList__c where name = :updatetableID limit 1];
            system.debug('updateTab -->' + updateTab);
            if (updateTab != null && updateTab.size() > 0) {
                for (TableList__c t: updateTab) {
                    t.status__C = 'ReadyForBill';
                    update t;
                }
            }
            else if (updateTab == null || updateTab.size() == 0) {
                List < opportunity__c > o = [select id, stagename__C from opportunity__c where id = :updateOppId limit 1];
                system.debug('Take away' + o);
                for (opportunity__c o1: o) {
                    o1.stagename__C = 'Delivered';
                    update o1;
                }
            }
            List < OrderTaking__c > ot = [select id, status__c from OrderTaking__c where opportunity__r.id = :updateOppId];
            for (OrderTaking__c order: ot) {
                order.status__c = 'Delivered';
                updateOrder.add(order);
            }
            if (updateOrder.size() > 0) update updateOrder;

        }
        PageReference pageRef = new PageReference('/apex/ServiceOrder');
        pageRef.setRedirect(true);
        return pageRef;
    }

    public PageReference incrementCounter() {
        roList = new List < resultOrder > ();
        takeawayroList = new List < resultOrder > ();
        opp = new List < OrderTaking__c > ();
        List < TableList__c > t = [select id, name, opportunitynew__r.id, status__c from TableList__c where Status__c = 'Serving'];
        for (TableList__c t1: t) {
            opp = [select id, name, Product__r.name, quantity__C, Price__C from OrderTaking__c
            where opportunity__r.id = :t1.opportunitynew__r.id and opportunity__r.type__c = 'New Customer'
            order by createddate desc];
            resultOrder r = new resultOrder(t1.name, t1.opportunitynew__r.id + '', opp);
           roList.add(r);

        }
        system.debug(oppStr);

        List < opportunity__c > oppt = [select id, OrderNumber__c, type__c from opportunity__c where type__c = 'TakeAway'
        and stagename__c <>'Delivered'
        and createddate = LAST_N_DAYS: 1];
        for (opportunity__c op1: oppt) {
            takeawayopp = [select id, Product__r.name, quantity__C, Price__C from OrderTaking__c where opportunity__r.id = :op1.id order by createddate desc];
            resultOrder r = new resultOrder(op1.OrderNumber__c, op1.id + '', takeawayopp);
            takeawayroList.add(r);
        }
        return null;
    }

}